# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  checkout_code:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v2-checkout-{{ .Branch }}

      - checkout

      - save_cache:
          paths:
            - .
            - .git
          key: v2-checkout-{{ .Branch }}

  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - v2-checkout-{{ .Branch }}

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  testing:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v2-checkout-{{ .Branch }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - restore_cache:
          keys:
            - v2-checkout-{{ .Branch }}
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
